language: java
dist: xenial
env:
  global:
    - MVN_CMD="./mvnw --settings .travis.settings.xml -e -B -V"
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
  - openjdk8
  - openjdk10
  - openjdk11

stages:
  - test
  - release

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.m2/wrapper

install: true
script: $MVN_CMD verify

jobs:
  include:
    - stage: release
      #      if: (tag =~ /^v[0-9]+\.[0-9]+\.[0-9]+((-.+)|($))/) AND (fork = false)
      if: fork = false AND tag IS NOT present AND type = push AND branch = release
      jdk: openjdk11
      install: true
      ## export GPG details
      before_script:
        - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
        - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
      script: $MVN_CMD install -DskipTests=true -Prelease

      before_deploy:
        # set project version from maven version
        - ./mvnw help:evaluate -N -Dexpression=project.version|grep -v '\['
        - export PROJECT_VERSION=$(./mvnw help:evaluate -N -Dexpression=project.version|grep -v '\[')
        # check if this is a snapshot version
        - export IS_SNAPSHOT=$(if [[ $PROJECT_VERSION == *"-SNAPSHOT" ]]; then echo true; else echo false;fi)
        # Set up git user name and tag this commit
        - git config --local user.name "Andreas Keefer (Travis CI)"
        - git config --local user.email "andreas.keefer@senacor.com"
        - export TRAVIS_TAG=${PROJECT_VERSION}-$(date --iso-8601=seconds)-$(git log --format=%h -1)
        - git tag $TRAVIS_TAG -m "Release ${PROJECT_VERSION}"

      deploy:
        - provider: script
          on:
            repo: senacor/elasticsearch-evolution
            tags: true
            condition: $IS_SNAPSHOT = false
          skip_cleanup: true
          script: bash $MVN_CMD deploy -DskipTests=true -Prelease
        - provider: releases
          on:
            repo: senacor/elasticsearch-evolution
            tags: true
            condition: $IS_SNAPSHOT = false
          skip_cleanup: true
          api_key:
            secure: mwrHbQxvIIiUEnCFWT7M83fonGSWVh7SpH/w1g6Md6eeJ1u2WJRnxFppoB3mBonGemGh9NFc2Fox+5L7y2g8X+YOPJJq4XSQqE5aK9LEz6fWo4qYLif8o05/EFU9m8So4BJ+KEPIG/gQWPWookJAw6MTFo7GFCCIW3TJCAQ0buWqNPNMFbJznrGo/6mL1MPes1rL0ukfMAOiaHnCXHraFgJIelRTCjdzd9iNOTxCjdvoTwtVqrhnllDhEQ0foeQVbN2X60fcN/NyuR2g/L4cCfRnpjTpuDSclWY/fwD9GzQPz9Oxk5kCL3eL0dQDJXQJgo3s2oldNz8vov5TANM3/dELGj2W04vDahxioz0z7QcvzaTPldr7lI08b6hw+i5+774Yjkgt9fwJ5bX+Z23baERJVTA9vSLFY9T+hfTv6cxUflIbzxW1b+kj13fzjISwClhxieQ0YXgz+jPVUSMM3oxvTAJwFimo4bIyeuUo4ESpfWVExVhC6FgQkjq+f3o+dSDIJf5jshqVv3g22p1qawwg9xZ8gy4MMD3K5zamMRFW8EbodRlEvcdah6lE6sBaNl4SWFNMq8EQFUewqeMnW/r8BRITNLfQXKLRDUc21NxbfgAaLL0lxBRJkiMwuGyougTc12DUTLHRDgLVU10IMbk5vNXuaDoKwiyROO+Y32o=
          file:
            - spring-boot-starter-elasticsearch-evolution/target/spring-boot-starter-elasticsearch-evolution-$PROJECT_VERSION.jar
            - elasticsearch-evolution-core/target/elasticsearch-evolution-core-$PROJECT_VERSION.jar
          draft: false
          name: $PROJECT_VERSION